from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import date, datetime
import sqlite3
import os.path

class Ui_MainWindow(object):
    def dateParser(self):
        the_date = self.dateEditInput.text()
        #print(datetime.strptime(date, '%b %d %Y').strftime('%d-%m-%Y'))
        return datetime.strptime(the_date, '%b %d %Y').strftime('%Y-%m-%d')
    
    def showDate(self):
         value = self.calendarWidget.selectedDate()
         return value.toPyDate()
         #print(value.toPyDate())
    
    def submitData(self):
        connection = sqlite3.connect('net-worth-tracker.db')
        c = connection.cursor()
        
        if self.dateEditInput.text() != '':
            date = self.dateParser()
        else:
            date = self.showDate()
            
        cashOnHand = float(self.cashonhandInput.text())
        assets = float(self.assetsInput.text())
        debt = float(self.debtInput.text())
        assetsDesc = self.assetsDescInput.toPlainText()
        netWorth = float(assets - debt)
        
        c.execute("INSERT INTO netWorthData (date, cashonhand, assets, debt, totalNetWorth, assetsDescription) VALUES (?, ?, ?, ?, ?, ?)",
                   (date, cashOnHand, assets, debt, netWorth, assetsDesc))
        connection.commit()
        connection.close()
    
    
    def loadData(self):
        BASE_DIR = os.path.dirname(os.path.abspath(__file__))
        db_path = os.path.join(BASE_DIR, "net-worth-tracker.db")
        with sqlite3.connect(db_path) as db:
            #connection = sqlite3.connect('net-worth-tracker.db')
            query = "SELECT * FROM netWorthData"
            #result = connection.execute(query)
            result = db.execute(query)
            self.tableWidget.setRowCount(0)
            
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))

            db.commit()
            db.close
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(882, 696)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 881, 691))
        self.tabWidget.setObjectName("tabWidget")
        self.inputTab = QtWidgets.QWidget()
        self.inputTab.setObjectName("inputTab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.inputTab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(170, 70, 281, 141))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setVerticalSpacing(20)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.assetsInput = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.assetsInput.setObjectName("assetsInput")
        self.gridLayout_9.addWidget(self.assetsInput, 1, 0, 1, 1)
        self.debtInput = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.debtInput.setObjectName("debtInput")
        self.gridLayout_9.addWidget(self.debtInput, 2, 0, 1, 1)
        self.cashonhandInput = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.cashonhandInput.setObjectName("cashonhandInput")
        self.gridLayout_9.addWidget(self.cashonhandInput, 0, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.inputTab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(30, 220, 421, 231))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.assetsDescInput = QtWidgets.QTextEdit(self.gridLayoutWidget_3)
        self.assetsDescInput.setObjectName("assetsDescInput")
        self.gridLayout_8.addWidget(self.assetsDescInput, 1, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_8.addWidget(self.label_15, 0, 2, 1, 1)
        self.submitButton = QtWidgets.QPushButton(self.inputTab)
        self.submitButton.setGeometry(QtCore.QRect(180, 480, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.submitButton.setFont(font)
        self.submitButton.setObjectName("submitButton")
        self.gridLayoutWidget = QtWidgets.QWidget(self.inputTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 60, 141, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 0, 0, 1, 1)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.inputTab)
        self.calendarWidget.setGeometry(QtCore.QRect(470, 20, 392, 211))
        self.calendarWidget.setObjectName("calendarWidget")
        self.selectDateButton = QtWidgets.QPushButton(self.inputTab)
        self.selectDateButton.setGeometry(QtCore.QRect(610, 240, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selectDateButton.setFont(font)
        self.selectDateButton.setObjectName("selectDateButton")
        self.dateLabel = QtWidgets.QLabel(self.inputTab)
        self.dateLabel.setGeometry(QtCore.QRect(80, 20, 91, 30))
        self.dateLabel.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.dateLabel.setFont(font)
        self.dateLabel.setObjectName("dateLabel")
        self.label_14 = QtWidgets.QLabel(self.inputTab)
        self.label_14.setGeometry(QtCore.QRect(30, 10, 139, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_17 = QtWidgets.QLabel(self.inputTab)
        self.label_17.setGeometry(QtCore.QRect(170, 10, 139, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.dateEditInput = QtWidgets.QLineEdit(self.inputTab)
        self.dateEditInput.setGeometry(QtCore.QRect(250, 20, 201, 24))
        self.dateEditInput.setObjectName("dateEditInput")
        self.tabWidget.addTab(self.inputTab, "")
        self.dashboardTab = QtWidgets.QWidget()
        self.dashboardTab.setObjectName("dashboardTab")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.dashboardTab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 20, 831, 291))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.dashboardGridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.dashboardGridLayout.setContentsMargins(0, 0, 0, 0)
        self.dashboardGridLayout.setObjectName("dashboardGridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget_4)
        self.tableWidget.setRowCount(11)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.dashboardGridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.refreshButton = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.refreshButton.setFont(font)
        self.refreshButton.setObjectName("refreshButton")
        ###
        self.refreshButton.clicked.connect(self.loadData)
        
        self.submitButton.clicked.connect(self.submitData)

        self.selectDateButton.clicked.connect(self.showDate)
        
        ###
        
        self.dashboardGridLayout.addWidget(self.refreshButton, 5, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.dashboardGridLayout.addWidget(self.label_16, 0, 0, 1, 1)
        self.tabWidget.addTab(self.dashboardTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 882, 26))
        self.menubar.setObjectName("menubar")
        self.menuInput = QtWidgets.QMenu(self.menubar)
        self.menuInput.setObjectName("menuInput")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiontets = QtWidgets.QAction(MainWindow)
        self.actiontets.setObjectName("actiontets")
        self.menubar.addAction(self.menuInput.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        # MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setWindowTitle("Net Worth Tracker")
        MainWindow.setWindowIcon(QtGui.QIcon("stats.png"))
        self.assetsInput.setPlaceholderText(_translate("MainWindow", "Php"))
        self.debtInput.setPlaceholderText(_translate("MainWindow", "Php"))
        self.cashonhandInput.setPlaceholderText(_translate("MainWindow", "Php"))
        self.assetsDescInput.setPlaceholderText(_translate("MainWindow", "Insert some text here"))
        self.label_15.setText(_translate("MainWindow", "Assets Description"))
        self.submitButton.setText(_translate("MainWindow", "Submit"))
        self.label_13.setText(_translate("MainWindow", "Debt"))
        self.label_11.setText(_translate("MainWindow", "Assets"))
        self.label_12.setText(_translate("MainWindow", "Cash On-Hand"))
        self.selectDateButton.setText(_translate("MainWindow", "Select Date"))
        ###
        self.dateLabel.setText(_translate("MainWindow", "> " + str(self.showDate())))
        self.label_14.setText(_translate("MainWindow", "Date"))
        self.label_17.setText(_translate("MainWindow", "Date Edit"))
        self.dateEditInput.setPlaceholderText(_translate("MainWindow", "Ex: Dec 20 2000"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.inputTab), _translate("MainWindow", "Input"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cash On-Hand"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Assets"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Debt"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Total Net Worth"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Assets Description"))
        self.refreshButton.setText(_translate("MainWindow", "Refesh"))
        self.label_16.setText(_translate("MainWindow", "Dashboard"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dashboardTab), _translate("MainWindow", "Dashboard"))
        self.menuInput.setTitle(_translate("MainWindow", "Menu"))
        self.actiontets.setText(_translate("MainWindow", "tets"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
